---
- name: Setup EPEL
  hosts: all
  tags: common
  tasks:
    - name: Disable SELinux for the demo
      selinux:
        policy: targeted
        state: permissive

    - name: Install EPEL
      yum:
          name: epel-release
          state: present

    - name: Add authorized key
      authorized_key:
        user: root
        key: '{{ demo_ssh_key_public }}'
        state: present

- name: Setup Ansible semaphore with requisities
  hosts: semaphore
  tags: semaphore
  roles:
    - role: geerlingguy.mysql
    - role: VerosK.nginx
    - role: local.semaphore
