semaphore_port: 3030
semaphore_overwrite_config: true
# populate config
semaphore_upload_db: "files/semaphore.sql"

semaphore_user: 'semaphore'
semaphore_home: /var/lib/semaphore

nginx_dhparam_bits: 512

nginx_sites:
  - name: semaphore
    is_default: true
    with_ssl: false
    request_acme_cert: false

    root_config: >
        location / {
                proxy_pass http://127.0.0.1:{{ semaphore_port }}/;
                proxy_read_timeout 90;
                proxy_set_header Host        $http_host;
                proxy_set_header X-Forwarded-Proto "http";
                proxy_set_header X-Forwarded-For $remote_addr;
        #       proxy_set_header X-Forwarded-User $remote_user;
                client_max_body_size    128m;
        }